apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcing-backend
  labels:
    app: mcing-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcing-backend
  template:
    metadata:
      labels:
        app: mcing-backend
    spec:
      containers:
        - name: mcing-backend
          image: mcing-backend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mcing-backend
  labels:
    app: mcing-backend
spec:
  selector:
    app: mcing-backend
  ports:
    - protocol: TCP
      port: 8080 # Serviceが公開するポート
      targetPort: 80 # Pod内のコンテナがリッスンしているポート
  type: ClusterIP # 外部に公開する場合はLoadBalancer、内部のみの場合はClusterIP
